version: '2'
services:

#     liga:
#         build: .
#         environment:
#             BOT_TOKEN: 1228088328:AAGo7QuhhmPm7McUFmaN7coSO5Oy66xZ29E
#             SOCS_PROXY: 78.46.218.20 # https://50na50.net/ru/proxy/socks5list
#             SOCS_PORT: 41714
#         command: ["node", "src/liga.js"]
#     n_bot:
#         build: .
#         environment:
#             BOT_TOKEN: '247414626:AAH-o9OdFJnJITL7-bsDejdAPgtaTxxzF-I'
#             SOCS_PROXY: 78.46.218.20 # https://50na50.net/ru/proxy/socks5list
#             SOCS_PORT: 41714
#         command: ["node", "src/liga.js"]

    bot:
        build:
          context: python_apps/bot
          dockerfile: Dockerfile
        environment:
          PROXY: 'socks5h://54.39.16.26:35385'
        volumes:
          - ./python_apps/bot:/code
        command: ["python", "bot.py"]

    db:
        image: postgres
#        restart: always
        environment:
            POSTGRES_PASSWORD: example

    adminer:
        image: adminer
#        restart: always
        ports:
            - 8080:8080
